#pragma once
#include <string>
#include "data/DCBiasCurveDatabase.h"

/*

Real DC-bias permeability roll-off for powder toroids (MPP/Kool Mu/High Flux/XFlux/Edge/Mix-26).

A powder core's catalog AL (DCBiasCurveDatabase's sibling, CoreData::al) is measured at ~0 A DC bias -
it is the material's INITIAL permeability, not a constant. As DC current rises, the core's actual
permeability rolls off (a real, well-documented powder-core property - not something Phase 1 previously
modeled at all: TurnsAndGapDesign.cpp's distributed-gap branch used to solve turns against the flat
catalog AL at every current level, silently overstating inductance at any nonzero current). This module
supplies the two pieces needed to correct that: the real DC magnetizing force at a given
(turns, current, path length), and the real manufacturer-published %initial-permeability-remaining curve
at that force.

Curve-fit coefficients (a/b/c/d below) are read verbatim from data/dc_bias_curves.csv - real
manufacturer-published values, not derived, fitted, or estimated by this project. A handful of rows were
hand-transcribed directly from Magnetics Inc.'s and Micrometals' own published "Permeability vs. DC Bias"
datasheet pages; most are generated by scripts/export_real_data.py's fetch_dc_bias_curves() from
PyOpenMagnetics' own per-material magneticFieldDcBiasFactor field (the same real vendor data, in a
different unit for H - see that function's docstring for the verified A/m-to-Oe conversion, cross-checked
against every hand-transcribed row before being trusted for the rest). Formula and units confirmed against
the vendors' own worked examples (see DCBiasCurveDatabase.h and this module's .cpp for the specific
cross-checks).

*/

//precondition: none
//postcondition: returns the DCBiasCurveDatabase row for materialName, if any. found == false if this
//material has no published DC-bias curve in the current dataset (e.g. any non-powder or ungapped-only
//material) - callers must treat that as "no roll-off model available," never assume 100% permeability.
struct DCBiasCurveLookup {
    bool found = false;
    //valid only when found == true
    DCBiasCurveData curve;
};

DCBiasCurveLookup findDCBiasCurve(const std::string& materialName);

//precondition: turns > 0, leMm > 0
//postcondition: returns the DC magnetizing force H (Oersteds) - H = 0.4*pi*N*I/le, le in cm - the standard
//formula used by both Magnetics Inc. and Micrometals' own DC-bias curves (confirmed against their published
//worked examples). currentA may be 0 (returns H=0, the curve's own 100%-permeability point).
double dcMagnetizingForceOe(int turns, double currentA, double leMm);

//precondition: curve came from a real DCBiasCurveDatabase row (DCBiasCurveLookup::found == true), hOe >= 0
//postcondition: returns %initial permeability remaining (0-100 scale, not a 0-1 fraction) via
//%mu = 1/(a + b*H^c) + d - clamped to [0, 100] since the raw formula can drift fractionally above 100 at
//H=0 for some materials' published coefficients (floating-point rounding on real datasheet values, not a
//sign the physics is wrong) and must never be read as more than fully-initial permeability.
double percentInitialPermeability(double hOe, const DCBiasCurveData& curve);
